# Multiple Linear Regression
## 50 start up Dataset
L'objectif est de prédire le profit des start up en se basant sur les dépenses dans différents domaines : R&D, admin marketing ,etc. 
<br>
Autrement dit, on cherche à savoir quelles variables ont le plus d'impact sur le profit. 

## Importing the libraries

In [14]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [36]:
dataset = pd.read_csv('50_Startups.csv')
X = # code ici
y = # code ici

In [37]:
print(X)

[[165349.2 136897.8 471784.1 'New York']
 [162597.7 151377.59 443898.53 'California']
 [153441.51 101145.55 407934.54 'Florida']
 [144372.41 118671.85 383199.62 'New York']
 [142107.34 91391.77 366168.42 'Florida']
 [131876.9 99814.71 362861.36 'New York']
 [134615.46 147198.87 127716.82 'California']
 [130298.13 145530.06 323876.68 'Florida']
 [120542.52 148718.95 311613.29 'New York']
 [123334.88 108679.17 304981.62 'California']
 [101913.08 110594.11 229160.95 'Florida']
 [100671.96 91790.61 249744.55 'California']
 [93863.75 127320.38 249839.44 'Florida']
 [91992.39 135495.07 252664.93 'California']
 [119943.24 156547.42 256512.92 'Florida']
 [114523.61 122616.84 261776.23 'New York']
 [78013.11 121597.55 264346.06 'California']
 [94657.16 145077.58 282574.31 'New York']
 [91749.16 114175.79 294919.57 'Florida']
 [86419.7 153514.11 0.0 'New York']
 [76253.86 113867.3 298664.47 'California']
 [78389.47 153773.43 299737.29 'New York']
 [73994.56 122782.75 303319.26 'Florida']
 [67532

## Encoding categorical data
Transformer les variables catégorielles en variables numériques

In [38]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
# encoding categorial data using OneHotEncoder 
ct = # code ici
# transform data 
X = # code ici

In [18]:
print(X)

[[0.0 0.0 1.0 165349.2 136897.8 471784.1]
 [1.0 0.0 0.0 162597.7 151377.59 443898.53]
 [0.0 1.0 0.0 153441.51 101145.55 407934.54]
 [0.0 0.0 1.0 144372.41 118671.85 383199.62]
 [0.0 1.0 0.0 142107.34 91391.77 366168.42]
 [0.0 0.0 1.0 131876.9 99814.71 362861.36]
 [1.0 0.0 0.0 134615.46 147198.87 127716.82]
 [0.0 1.0 0.0 130298.13 145530.06 323876.68]
 [0.0 0.0 1.0 120542.52 148718.95 311613.29]
 [1.0 0.0 0.0 123334.88 108679.17 304981.62]
 [0.0 1.0 0.0 101913.08 110594.11 229160.95]
 [1.0 0.0 0.0 100671.96 91790.61 249744.55]
 [0.0 1.0 0.0 93863.75 127320.38 249839.44]
 [1.0 0.0 0.0 91992.39 135495.07 252664.93]
 [0.0 1.0 0.0 119943.24 156547.42 256512.92]
 [0.0 0.0 1.0 114523.61 122616.84 261776.23]
 [1.0 0.0 0.0 78013.11 121597.55 264346.06]
 [0.0 0.0 1.0 94657.16 145077.58 282574.31]
 [0.0 1.0 0.0 91749.16 114175.79 294919.57]
 [0.0 0.0 1.0 86419.7 153514.11 0.0]
 [1.0 0.0 0.0 76253.86 113867.3 298664.47]
 [0.0 0.0 1.0 78389.47 153773.43 299737.29]
 [0.0 1.0 0.0 73994.56 122782.75 3

Préparer le dataset de training et de test

In [96]:


## Splitting the dataset into the Training set and Test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)



Ecrire une fonction qui permet d'entrainer un modèle de régression et de retourner les métriques d'évaluation (mae, mse, rmse, R²,R²-ajusté 

In [ ]:
# function the return metrics of linear regression
def linearRegression (X_train, X_test, y_train, y_test) : 
    
    ## Training the Multiple Linear Regression model on the Training set
    regressor = # code ici 
    regressor.fit(X_train, y_train)
    ### Predicting the Test set results
    y_pred = # code ici 
    coef= # code ici 
    mae = # code ici 
    mse = # code ici 
    rmse = # code ici 
    r2 = # code ici 
    adj_r2 =# code ici 
    print('Coefficients : ',regressor.coef_)
    print('MAE : ',mae)
    print('MSE : ',mse)
    print('R² : ',r2)
    print('Adjusted R² : ',adj_r2)
    return [mae,mse,rmse,r2,adj_r2]

#### Modèle 1 
Construire un modèle de régression linéaire avec l'ensemble des données d'entraînement. 

In [97]:
# model with all features 
lm1 = linearRegression(X,y)

Coefficients :  [ 8.66e+01 -8.73e+02  7.86e+02  7.73e-01  3.29e-02  3.66e-02]
MAE :  7514.2936596413765
MSE :  83502864.03259295
R² :  0.9347068473282303
Adjusted R² :  0.8041205419846909


#### Modèle 2
Construire un modèle de régression linéaire avec les variables explicatives 0

In [98]:
# model with  features 0, 1, 3, 4, 5
lm2 = linearRegression(X[:, [0, 1, 3, 4, 5]],y)

Coefficients :  [-6.99e+02 -1.66e+03  7.73e-01  3.29e-02  3.66e-02]
MAE :  7514.293659644447
MSE :  83502864.03246719
R² :  0.9347068473283286
Adjusted R² :  0.8530904064887395


In [99]:
# model with  features 0, 3, 5
lm3 = linearRegression(X[:, [0, 3, 5]],y)

Coefficients :  [20.32  0.79  0.03]
MAE :  6888.168358196924
MSE :  67229760.13443592
R² :  0.947431228336901
Adjusted R² :  0.9211468425053515


In [100]:
# model with  features 0, 3
lm4 = linearRegression(X[:, [0, 3]],y)

Coefficients :  [-308.77    0.85]
MAE :  6802.727094890668
MSE :  68148935.31566742
R² :  0.9467125003491181
Adjusted R² :  0.9314875004488662


In [104]:
lms = [lm1,lm2,lm3,lm4]
df = pd.DataFrame(lms, index=['Model 1','Model 2','Model 3','Model 4'],columns =['MAE', 'MSE', 'RMSE','R²','Adjusted R²'], dtype = float) 
df 

MAE           MSE         RMSE        R²  Adjusted R²
Model 1  7514.293660  8.350286e+07  9137.990153  0.934707     0.804121
Model 2  7514.293660  8.350286e+07  9137.990153  0.934707     0.853090
Model 3  6888.168358  6.722976e+07  8199.375594  0.947431     0.921147
Model 4  6802.727095  6.814894e+07  8255.236842  0.946713     0.931488

### Conclure